# basics
user_name: "sjtu-jhw"
repo_name: "ResearchTracker"
max_results: 50

# file paths
md_readme_path: 'README.md'

# GPT
gpt: False

# keywords to search
keywords:
    # "OCR": 
    #     filters: ["OCR", "Character Recognition"]
    "Document Analysis":
        filters: ["Document Analysis", "Layout Analysis", "OCR", "Document Parsing"]
