# basics
user_name: "sjtu-jhw"
repo_name: "ResearchTracker"
max_results: 50

# file paths
md_readme_path: 'README.md'

# GPT
gpt: True

# keywords to search
keywords:
    "Document Analysis":
        filters: ["Document Analysis", "Layout Analysis", "OCR", "Document Parsing", "Document Content Analysis"]
    "Data Centric":
        filters: ["Data Centric", ]
    "LLM":
        filters: ["LLM", "Language Model", "Vision-Language Models", "Large Language Model"]
