# test workflow

name: Run Test

on:
  workflow_dispatch

env:
  GITHUB_USER_NAME: sjtu-jhw
  GITHUB_USER_EMAIL: jhw15763365981@gmail.com

jobs:
  build:
    name: update
    runs-on: ubuntu-latest

    steps:
    - name: test
      run: ifconfig
